format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$golang\
$nodejs\
$python\
$cmd_duration $time\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "bold italic blue"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold bright-purple"

[git_status]
staged = "[++$count](green)"
format = "([$all_status$ahead_behind$modified]($style) )"
style = "bold bright-orange"

[git_state]
format = "[$state( $progress_current/$progress_total)]($style)"
style = "bold bright-orange"

[git_metrics]
disabled = false

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[golang]
symbol = "ﳑ "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold italic black"
format = "[$time]($style)"
